services:
  stb:
    build:
      context: ./services/STB
      dockerfile: Dockerfile
    container_name: stb-service
    ports:
      - "8001:8001"
    restart: unless-stopped

  aes:
    build:
      context: ./services/AES
      dockerfile: Dockerfile
    container_name: aes-service
    ports:
      - "8002:8002"
    restart: unless-stopped